function [fitresult, gof, h] = createFit_poly3(data)
%CREATEFIT(DATA_12_SUB5)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: data_12_sub5
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 30-Jun-2021 17:42:48


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( [], data );

% Set up fittype and options.
ft = fittype( 'poly3' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
s = inputname(1); % get name of data set

figure( 'Name', s);
h = plot( fitresult, xData, yData );
ylim([0 1]);
legend(h, s, '3rd order polynomial fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
ylabel( s, 'Interpreter', 'none' );
xlabel('morph levels');
grid on
